name: Dotnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
        runtime: [ 'win-x64' ]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Build
      run: |
        dotnet publish -r ${{ matrix.runtime }} --configuration ${{ matrix.configuration }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts ${{ matrix.configuration }} ${{ matrix.runtime }}
        path: artifacts/publish/XDLCompiler/${{ matrix.configuration }}_${{ matrix.runtime }}/**
        if-no-files-found: error

  trigger_release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ success() && startsWith( github.ref, 'refs/tags' ) }}
    steps: 
    - name: Trigger release on tag
      run: |
        echo Trigger release on a tag
        gh workflow run --ref ${{ github.ref_name }} Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}