name: Release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get run ID
        id: get-run-id
        env:
          - WF_NAME: Dotnet
        run: |
          OTHER_REPO="${{ github.repository }}"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          # Download all artifacts from that run
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Create zip archives
        run: |
          for dir in *; do 7z a "${dir}.zip" "${dir}"; done

      - name: Show directory structure
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
